apiVersion: batch/v1
kind: Job
metadata:
  name: seanc-task5job
spec:
  template:
    spec:
      containers:
      - name: seanc-task5job
        image: stablebaselines/stable-baselines3
        command:
        - sh
        - -c
        - "cd /pvcvolume && git clone https://github.com/SeanC0112/Task-5 && cd Task-5 && bash bashScript.sh"
        volumeMounts:
        - name: pvcvolume
          mountPath: /pvcvolume
        resources:
          limits:
            memory: 32Gi
            cpu: "8"
            nvidia.com/gpu: 1
          requests:
            memory: 16Gi
            cpu: "4"
            nvidia.com/gpu: 1
      volumes:
      - name: pvcvolume
        persistentVolumeClaim:
          claimName: seanc-task5pvc
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: nvidia.com/gpu.product
      #           operator: In
      #           values:
      #           - NVIDIA-A10
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
